### ISSUE TITLE
throttle tests failing

### ISSUE THREAD

**Issue by rsichny** [pohmelie/aioftp#19]
if for some reason the network or pathio is slow then the tests result in error (actually because "magic numbers" are used as a perfect time):
```
python tests/test-throttle.py 
INFO:aioftp:aioftp server: serving on 0.0.0.0:8888
INFO:aioftp:aioftp server: new connection from 127.0.0.1:36665
INFO:aioftp:aioftp server: 220 welcome
INFO:aioftp:aioftp client: 220 welcome
INFO:aioftp:aioftp client: USER anonymous
INFO:aioftp:aioftp server: USER anonymous
INFO:aioftp:aioftp server: 230 anonymous login
INFO:aioftp:aioftp client: 230 anonymous login
INFO:aioftp:aioftp client: TYPE I
INFO:aioftp:aioftp server: TYPE I
INFO:aioftp:aioftp server: 200 
INFO:aioftp:aioftp client: 200
INFO:aioftp:aioftp client: PASV
INFO:aioftp:aioftp server: PASV
INFO:aioftp:aioftp server: 227-listen socket created
INFO:aioftp:aioftp server: 227 (0,0,0,0,203,221)
INFO:aioftp:aioftp client: 227-listen socket created
INFO:aioftp:aioftp client: 227 (0,0,0,0,203,221)
INFO:aioftp:aioftp client: STOR tests/foo/foo.txt
INFO:aioftp:aioftp server: STOR tests/foo/foo.txt
INFO:aioftp:aioftp server: 150 data transfer started
INFO:aioftp:aioftp client: 150 data transfer started
INFO:aioftp:aioftp server: 226 data transfer done
INFO:aioftp:aioftp client: 226 data transfer done
INFO:aioftp:aioftp server: closing connection from 127.0.0.1:36665
INFO:aioftp:aioftp server: serving on 0.0.0.0:8888
INFO:aioftp:aioftp server: new connection from 127.0.0.1:36667
INFO:aioftp:aioftp server: 220 welcome
INFO:aioftp:aioftp client: 220 welcome
INFO:aioftp:aioftp client: USER anonymous
INFO:aioftp:aioftp server: USER anonymous
INFO:aioftp:aioftp server: 230 anonymous login
INFO:aioftp:aioftp client: 230 anonymous login
INFO:aioftp:aioftp client: TYPE I
INFO:aioftp:aioftp server: TYPE I
INFO:aioftp:aioftp server: 200 
INFO:aioftp:aioftp client: 200
INFO:aioftp:aioftp client: PASV
INFO:aioftp:aioftp server: PASV
INFO:aioftp:aioftp server: 227-listen socket created
INFO:aioftp:aioftp server: 227 (0,0,0,0,190,67)
INFO:aioftp:aioftp client: 227-listen socket created
INFO:aioftp:aioftp client: 227 (0,0,0,0,190,67)
INFO:aioftp:aioftp client: STOR tests/foo/foo.txt
INFO:aioftp:aioftp server: STOR tests/foo/foo.txt
INFO:aioftp:aioftp server: 150 data transfer started
INFO:aioftp:aioftp client: 150 data transfer started
INFO:aioftp:aioftp server: 226 data transfer done
INFO:aioftp:aioftp client: 226 data transfer done
INFO:aioftp:aioftp server: closing connection from 127.0.0.1:36667
Traceback (most recent call last):
  File "/home/roman/workspace/aioftp/tests/common.py", line 121, in wrapper
    yield from f(*args, tmp_dir=tmp_dir)
  File "tests/test-throttle.py", line 137, in test_client_write_throttle
    nose.tools.ok_(2.5 < (time.perf_counter() - start) < 3.5)
  File "/home/roman/workspace/aioftp/env/lib/python3.5/site-packages/nose/tools/trivial.py", line 22, in ok_
    raise AssertionError(msg)
AssertionError: None
```

IMO testing throttle this way is not fully correct.

PS. also, why don't you use loop.time() instead of time.perf_counter()?

**Comment by pohmelie** [comment]
How slow should be connection/path operations? I thought this is impossible for such tests (100Kib per second speed). How can we test speed without some hardcoded bounds? What test mechanic is better?
perf_counter is most accurate for current platform, but you are right, we don't need such precission here.

**Comment by rsichny** [comment]
well, on my PC it was always failing. But guess i've found the reason: https://github.com/pohmelie/aioftp/pull/20
