### ISSUE TITLE
Human logging

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/aioftp#32]
[As discussed](https://github.com/pohmelie/aioftp/commit/59161c73ec13af9a2d3a2a862ab5c92ce56cea3d?diff=unified#commitcomment-14212034) we need more elegant logging. But if we add some context via `extra` argument for more flexible formatting and user decide to use extended format via basicConfig, then he **must** pass those extra in every call of logging.
```python
import logging


top = logging.getLogger("top")
top.addHandler(logging.NullHandler())

real = logging.getLogger("top.yoba")


def yoba():

    real.error("FOO", extra={"foo": "bar"})
    logging.error("BAR")


if __name__ == "__main__":

    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s %(message)s extra['foo'] = %(foo)s",
    )
    yoba()
```
```
2015-11-06 07:09:34,871 FOO extra['foo'] = bar
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 568, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 537, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 381, in format
    return self._fmt % record.__dict__
KeyError: 'foo'
Call stack:
  File "./prog.py", line 22, in <module>
  File "./prog.py", line 13, in yoba
Message: 'BAR'
Arguments: ()
```
The solution looks like this:
```python
import logging


top = logging.getLogger("top")
top.addHandler(logging.NullHandler())

real = logging.getLogger("top.yoba")


def yoba():

    real.error("FOO", extra={"foo": "bar"})
    logging.error("BAR")


if __name__ == "__main__":

    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s %(message)s [base]",
    )

    top.propagate = False
    h = logging.StreamHandler()
    f = logging.Formatter(fmt="%(asctime)s %(message)s extra['foo'] = %(foo)s")
    h.setFormatter(f)
    top.addHandler(h)
    yoba()
```
```
2015-11-06 10:22:49,753 FOO extra['foo'] = bar
2015-11-06 10:22:49,754 BAR [base]
```
But, is this friendly and simple enough to end user? Of course, he can use basicConfig without configuring extra handler and loose some context.

**Comment by pohmelie** [comment]
Also, I've watched `requests` and `aiohttp` for logging. And `aiohttp` can use custom logger, which passed as argument. Probably this is good idea.
