### ISSUE TITLE
KeyError: 'type' from ClientSession.is_file

### ISSUE THREAD

**Issue by thelostt** [pohmelie/aioftp#44]
This code:

    await client.download(source=remote_path, destination=local_path, write_into=True)

Throws a `KeyError` at:

    File "/usr/lib/python3.6/site-packages/aioftp/client.py", line 597, in is_file
        return info["type"] == "file"

However, the `type` keyword is visible from the client.list() function:

    [(PurePosixPath('a.xml'), {'type': 'file', ...

I'm using the 0.6.1 version (default pip installation).

**Comment by pohmelie** [comment]
Hm, pretty strange. Can you paste result of `await client.stat(remote_path)` here?

**Comment by thelostt** [comment]
It's returning a `{'': ''}` every time. Do you think it's anything to do with my ftp server's configuration instead?

**Comment by pohmelie** [comment]
Set client logger level to `INFO`
``` python
logging.getLogger("aioftp.client").setLevel(logging.INFO)
```
And paste here part of MLST request and response logging.

**Comment by thelostt** [comment]
Here:

```
INFO:aioftp.client:227 Entering Passive Mode (198,54,126,99,47,92)
INFO:aioftp.client:MLSD
INFO:aioftp.client:150 Accepted data connection
INFO:aioftp.client:MLST a.xml
INFO:aioftp.client:226-Options: -a -l
INFO:aioftp.client:226 5 matches total
INFO:aioftp.client:QUIT
INFO:aioftp.client:250-Begin
INFO:aioftp.client: type=file;size=10;modify=20170227161813;UNIX.mode=0644;UNIX.uid=1449;UNIX.gid=1445;unique=fd01g742014e; a.xml
INFO:aioftp.client:250 End.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<download_folder() done, defined at async_ftp.py:10> exception=KeyError('type',)>
Traceback (most recent call last):
  File "async_ftp.py", line 18, in download_folder
    await ftp.download(source=remote_path, destination=local_path, write_into=True)
  File "/usr/lib/python3.6/site-packages/aioftp/client.py", line 830, in download
    if await self.is_file(source):
  File "/usr/lib/python3.6/site-packages/aioftp/client.py", line 597, in is_file
    return info["type"] == "file"
KeyError: 'type'

```

**Comment by pohmelie** [comment]
Can you isolate single request (`await client.stat(path_to_file)`) to ftp server and paste output.

**Comment by thelostt** [comment]
Code:

```python
import aioftp
import asyncio

async def test_stat(host, login, passwd):
    async with aioftp.ClientSession(host, 21, login, passwd) as client:
        async for path, info in client.list():
            print(await client.stat(path))

ftp_info = {
    'host': 'x',
    'login': 'x',
    'passwd': 'x',
}

loop = asyncio.get_event_loop()
task = [test_stat(**ftp_info)]
loop.run_until_complete(asyncio.wait(task))
loop.close()

```

Log:

```
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
[...] Connection stuff [...]
INFO:aioftp.client:230-OK. Current restricted directory is /
INFO:aioftp.client:230 0 Kbytes used (0%) - authorized: 2048000 Kb
INFO:aioftp.client:TYPE I
INFO:aioftp.client:200 TYPE is now 8-bit binary
INFO:aioftp.client:PASV
INFO:aioftp.client:227 Entering Passive Mode (198,54,126,99,47,9)
INFO:aioftp.client:MLSD
INFO:aioftp.client:150 Accepted data connection
INFO:aioftp.client:MLST .ftpquota
INFO:aioftp.client:226-Options: -a -l
INFO:aioftp.client:226 4 matches total
INFO:aioftp.client:MLST test
INFO:aioftp.client:250-Begin
INFO:aioftp.client: type=file;size=5;modify=20170227161816;UNIX.mode=0600;UNIX.uid=1449;UNIX.gid=1445;unique=fd01g7420148; .ftpquota
INFO:aioftp.client:250 End.
INFO:aioftp.client:250-Begin
INFO:aioftp.client: type=dir;sizd=4096;modify=20170227161813;UNIX.mode=0755;UNIX.uid=1449;UNIX.gid=1445;unique=fd01g7420136; test
INFO:aioftp.client:250 End.
INFO:aioftp.client:TYPE I
INFO:aioftp.client:200 TYPE is now 8-bit binary
INFO:aioftp.client:PASV
INFO:aioftp.client:227 Entering Passive Mode (198,54,126,99,47,63)
INFO:aioftp.client:MLSD test
INFO:aioftp.client:150 Accepted data connection
INFO:aioftp.client:MLST test/a.xml
INFO:aioftp.client:226-Options: -a -l
INFO:aioftp.client:226 5 matches total
INFO:aioftp.client:MLST test/b.xml
INFO:aioftp.client:250-Begin
INFO:aioftp.client: type=file;size=10;modify=20170227161813;UNIX.mode=0644;UNIX.uid=1449;UNIX.gid=1445;unique=fd01g742014e; test/a.xml
INFO:aioftp.client:250 End.
INFO:aioftp.client:MLST test/inner
INFO:aioftp.client:250-Begin
INFO:aioftp.client: type=file;size=10;modify=20170227161813;UNIX.mode=0644;UNIX.uid=1449;UNIX.gid=1445;unique=fd01g742014c; test/b.xml
INFO:aioftp.client:250 End.
INFO:aioftp.client:250-Begin
INFO:aioftp.client: type=dir;sizd=4096;modify=20170227161816;UNIX.mode=0755;UNIX.uid=1449;UNIX.gid=1445;unique=fd01g742014f; test/inner
INFO:aioftp.client:250 End.
INFO:aioftp.client:TYPE I
INFO:aioftp.client:200 TYPE is now 8-bit binary
INFO:aioftp.client:PASV
INFO:aioftp.client:227 Entering Passive Mode (198,54,126,99,47,85)
INFO:aioftp.client:MLSD test/inner
INFO:aioftp.client:150 Accepted data connection
INFO:aioftp.client:MLST test/inner/c.xml
INFO:aioftp.client:226-Options: -a -l
INFO:aioftp.client:226 3 matches total
INFO:aioftp.client:250-Begin
INFO:aioftp.client: type=file;size=10;modify=20170227161816;UNIX.mode=0644;UNIX.uid=1449;UNIX.gid=1445;unique=fd01g7420150; test/inner/c.xml
INFO:aioftp.client:250 End.
INFO:aioftp.client:QUIT
INFO:aioftp.client:221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
INFO:aioftp.client:221 Logout.

```

Output from `test_stat`:

```
.ftpquota {'': ''}
test {'type': 'file', 'size': '5', 'modify': '20170227161816', 'unix.mode': '0600', 'unix.uid': '1449', 'unix.gid': '1445', 'unique': 'fd01g7420148'}
test/a.xml {'': ''}
test/b.xml {'type': 'file', 'size': '10', 'modify': '20170227161813', 'unix.mode': '0644', 'unix.uid': '1449', 'unix.gid': '1445', 'unique': 'fd01g742014e'}
test/inner {'type': 'file', 'size': '10', 'modify': '20170227161813', 'unix.mode': '0644', 'unix.uid': '1449', 'unix.gid': '1445', 'unique': 'fd01g742014c'}
test/inner/c.xml {'': ''}
```

Some files don't return their stat, so I assume you just have to handle cases where it's impossible to retrieve their stat?

**Comment by pohmelie** [comment]
I got it. The problem is on client side. `list` is lazy, so you can't do anything with server until you end `list` command. So you need collect `list` files and then download/stat/remove them. This is my bad, that this is not explained in documentation. More to say, front example of documentation is totally wrong (I will fix it!).
So, for proper work you need this:
``` python
async def test_stat(host, login, passwd):
    async with aioftp.ClientSession(host, 21, login, passwd) as client:
        for path, info in (await client.list()):
            print(await client.stat(path))
```
If you use straight download, then everything is done automatically:
``` python
async def test_download(host, login, passwd):
    async with aioftp.ClientSession(host, 21, login, passwd) as client:
        await client.download(".", "foo")
```

**Comment by pohmelie** [comment]
Or you can use two clients. One for lazy list, one for downloading.

**Comment by thelostt** [comment]
Alright, it did fix the issue on my end. Thanks.

**Comment by pohmelie** [comment]
Add extra note about `async for` and `list`:
http://aioftp.readthedocs.io/client_tutorial.html#listing-paths
http://aioftp.readthedocs.io/client_api.html#aioftp.Client.list

@thelostt, what do you think, is it good enough?

**Comment by thelostt** [comment]
> It means, that until you leave async for block you can’t interact with server.

It would be clearer to word that like so:

    It means that you can't interact with server until you leave async
for block.

But that's my opinion. Other than that, everything's pretty good.
