### ISSUE TITLE
KeyError: 'type' on 

### ISSUE THREAD

**Issue by myuriy** [pohmelie/aioftp#53]
Unhandled KeyError can get with Synology FTP server (i've print lines for debug):

2017-06-06 10:29:33,555 INFO ftp Trying to connect with 192.168.208.252
2017-06-06 10:29:33,631 INFO aioftp.client 220 NASDS415 FTP server ready.
2017-06-06 10:29:33,632 INFO aioftp.client USER ftpuser
2017-06-06 10:29:33,657 INFO aioftp.client 331 Password required for ftpuser.
2017-06-06 10:29:33,657 INFO aioftp.client PASS password
2017-06-06 10:29:33,955 INFO aioftp.client 230 User ftpuser logged in, access restrictions apply.
2017-06-06 10:29:33,956 INFO aioftp.client TYPE I
2017-06-06 10:29:34,180 INFO aioftp.client 200 Type set to I.
2017-06-06 10:29:34,180 INFO aioftp.client PASV
2017-06-06 10:29:34,401 INFO aioftp.client 227 Entering Passive Mode (192,168,208,252,217,7)
2017-06-06 10:29:34,425 INFO aioftp.client MLSD /
2017-06-06 10:29:34,446 INFO aioftp.client 150 Opening BINARY mode data connection for 'file list'.
b'type=file;modify=20170512000615;size=28676;UNIX.mode=0777;UNIX.owner=ftpuser;UNIX.group=users; .DS_Store\r\n'
b'type=dir;modify=20170508091520;size=1608;UNIX.mode=0000;UNIX.owner=root;UNIX.group=root; #recycle\r\n'
...
b'type=file;modify=20170606072933;size=218627167;UNIX.mode=0777;UNIX.owner=ftpuser;UNIX.group=users; results-00:d0:24:44:4d:70.txt\r\n'
b'type=file;modify=20170531094900;size=14947708;UNIX.mode=0777;UNIX.owner=ftpuser;UNIX.group=users; results-00:d0:24:44:d6:9c.txt\r\n'
2017-06-06 10:29:34,750 INFO aioftp.client 226 Transfer complete.
2017-06-06 10:29:34,751 INFO aioftp.client TYPE I
2017-06-06 10:29:34,775 INFO aioftp.client 200 Type set to I.
2017-06-06 10:29:34,775 INFO aioftp.client PASV
2017-06-06 10:29:34,796 INFO aioftp.client 227 Entering Passive Mode (192,168,208,252,217,8)
2017-06-06 10:29:34,816 INFO aioftp.client MLSD /#recycle
2017-06-06 10:29:34,835 INFO aioftp.client 150 Opening BINARY mode data connection for 'file list'.
b'ftpd: /#recycle: No such file or directory.\r\n'
2017-06-06 10:29:34,836 INFO aioftp.client QUIT
2017-06-06 10:29:34,836 INFO aioftp.client 226 Transfer complete.
Traceback (most recent call last):
  File "./bin/tools.py", line 111, in <module>
    cli(obj=dict(inventory=None))
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/Projects/tools/app/bin/commands.py", line 33, in do_fetch
    loop.run_until_complete(servers[0])
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/user/Projects/tools/app/bin/commands.py", line 46, in handle_download
    files = await client.list("/", recursive=True)
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/aioftp/common.py", line 135, in _to_list
    async for item in self:
  File "/Users/user/.virtualenvs/venv/lib/python3.6/site-packages/aioftp/client.py", line 754, in __anext__
    if info["type"] == "dir" and recursive:
KeyError: 'type'
(venv) user@macbook app

**Comment by pohmelie** [comment]
* Server tells client that there is `/#recycle` directory:
`b'type=dir;modify=20170508091520;size=1608;UNIX.mode=0000;UNIX.owner=root;UNIX.group=root; #recycle\r\n'`
* Client want to know content of `/#recycle`
`2017-06-06 10:29:34,816 INFO aioftp.client MLSD /#recycle`
* Server tells client that there is no such directory
`b'ftpd: /#recycle: No such file or directory.\r\n'`

It looks like it is a server-side issue or permissions problem. AFAIK if there is no such directory, server should not accept `MLSD` with `150` code, it should return `4xx`/`5xx` code.

**Comment by myuriy** [comment]
I disagree with you and here's why:

user@macbook tmp$ mkdir -p perms_test/only_for_root
user@macbook tmp$ mkdir -p perms_test/for_all
user@macbook tmp$ sudo chown root perms_test/only_for_root
user@macbook tmp$ sudo chmod 0700 perms_test/only_for_root
user@macbook tmp$ ls -la perms_test
total 0
drwxr-xr-x   4 user  wheel  136 Jun  6 18:15 .
drwxrwxrwt  28 root  wheel  952 Jun  6 18:15 ..
drwxr-xr-x   2 user  wheel   68 Jun  6 18:15 for_all
drwx------   2 root  wheel   68 Jun  6 18:15 only_for_root
user@macbook tmp$ ls -la perms_test/only_for_root/
ls: : Permission denied
user@macbook tmp$

**Comment by pohmelie** [comment]
* Server does not send `perm`, it sends `UNIX.mode=0000;UNIX.owner=root;UNIX.group=root;` and this facts are [OS-specific](https://tools.ietf.org/html/rfc3659#section-7.5).
* What behavior do you expect?

**Comment by pohmelie** [comment]
Also, `Permission denied` differs from `b'ftpd: /#recycle: No such file or directory.\r\n'`, isn't it?

**Comment by myuriy** [comment]
It seems that you are right - https://tools.ietf.org/html/rfc3659#section-7.2.1. I'm very sorry for the time spent.

**Comment by pohmelie** [comment]
No problem! :wink:
